/*
 * This source file was generated by the Gradle 'init' task
 */
package com.agentpatterns;

import org.junit.jupiter.api.Test;
import java.io.ByteArrayInputStream;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void mainRunsWithoutError() {
        System.setIn(new ByteArrayInputStream("World\nexit\n".getBytes()));
        assertDoesNotThrow(() -> App.main(new String[] {}));
    }
}
