/*
 * This source file was generated by the Gradle 'init' task
 */
package com.agentpatterns;

import org.junit.jupiter.api.Test;
import java.io.ByteArrayInputStream;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void mainRunsWithoutError() {
        // Exits immediately so no real LLM call is made (no test credentials available).
        System.setIn(new ByteArrayInputStream("exit\n".getBytes()));
        assertDoesNotThrow(() -> App.main(new String[] {}));
    }

    @Test void ragPatternRunsWithoutError() {
        System.setIn(new ByteArrayInputStream("exit\n".getBytes()));
        assertDoesNotThrow(() -> App.main(new String[] {"rag"}));
    }

    @Test void menuSelectRagThenExit() {
        System.setIn(new ByteArrayInputStream("4\nexit\n".getBytes()));
        assertDoesNotThrow(() -> App.main(new String[] {}));
    }
}
