[versions]
springBoot = "3.5.16"
springAi = "1.1.8"

[libraries]
spring-boot-bom = { module = "org.springframework.boot:spring-boot-dependencies", version.ref = "springBoot" }
spring-ai-bom = { module = "org.springframework.ai:spring-ai-bom", version.ref = "springAi" }

[plugins]
spring-boot = { id = "org.springframework.boot", version.ref = "springBoot" }
