/*
 * This source file was generated by the Gradle 'init' task
 */
package com.agentpatterns;

import java.util.Scanner;
import org.springframework.boot.CommandLineRunner;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

@SpringBootApplication
public class App implements CommandLineRunner {
    public static void main(String[] args) {
        SpringApplication.run(App.class, args);
    }

    @Override
    public void run(String... args) {
        try (Scanner scanner = new Scanner(System.in)) {
            System.out.println("Type your name and press Enter (type 'exit' to quit).");
            while (true) {
                System.out.print("What's your name? ");
                String name = scanner.nextLine().trim();
                if (name.equalsIgnoreCase("exit")) {
                    System.out.println("Bye!");
                    break;
                }
                System.out.println("Hello, " + name + "!");
            }
        }
    }
}
