/*
 * This source file was generated by the Gradle 'init' task
 */
package com.agentpatterns;

import java.util.Scanner;

import org.springframework.ai.chat.client.ChatClient;
import org.springframework.boot.CommandLineRunner;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

@SpringBootApplication
public class App implements CommandLineRunner {

    private final ChatClient chatClient;

    public App(ChatClient.Builder chatClientBuilder) {
        this.chatClient = chatClientBuilder.build();
    }

    public static void main(String[] args) {
        SpringApplication.run(App.class, args);
    }

    @Override
    public void run(String... args) {
        try (Scanner scanner = new Scanner(System.in)) {
            System.out.println("Chat with the app (type 'exit' to quit).");
            while (true) {
                System.out.print("> ");
                String input = scanner.nextLine().trim();
                if (input.equalsIgnoreCase("exit")) {
                    System.out.println("Bye!");
                    break;
                }
                if (input.isEmpty()) {
                    continue;
                }
                String response = chatClient.prompt(input).call().content();
                System.out.println(response);
            }
        }
    }
}
